# Generated by Django 2.0.2 on 2018-03-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackspot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.CharField(blank=True, help_text='Enter a description for this album', max_length=500),
        ),
    ]
