# Generated by Django 2.0.2 on 2018-03-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackspot', '0002_album_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description for this album', max_length=1000),
        ),
    ]
