# Generated by Django 2.0.3 on 2018-03-28 22:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackspot', '0003_auto_20180326_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_pic',
            field=models.CharField(help_text='Enter a URL for the artist picture', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(help_text='Enter a URL for the profile pic for this user', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trackspot.Album'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trackspot.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.CharField(blank=True, help_text='Enter a description for this song', max_length=2000),
        ),
    ]
