# Generated by Django 2.0.2 on 2018-04-10 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trackspot', '0005_album_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for this user', max_length=50)),
                ('bio', models.CharField(help_text='Enter a bio for this user', max_length=500)),
                ('location', models.CharField(help_text='Enter a location for this user', max_length=50)),
                ('profile_pic', models.CharField(help_text='Enter a URL for the profile pic for this user', max_length=500, null=True)),
                ('organization', models.CharField(help_text='Enter a location for this user', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='critic',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Critic',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
